### ISSUE TITLE
Some pybloqs rendering is broken in Python 3.8

### ISSUE THREAD

**Issue by danyaalm** [man-group/notebooker#167]
Some Pybloqs Block elements are being squashed when rendering in Notebooker

![image](https://github.com/man-group/notebooker/assets/54478623/5d87bd8a-feb1-4ee4-985e-8e28ca1e7f75)

**Comment by jonbannister** [comment]
@danyaalm could we get a minimal reproducible example please?

**Comment by jonbannister** [comment]
Confirmed as being a user issue rather than a py38 issue.
