### ISSUE TITLE
Notebooker input widgets support

### ISSUE THREAD

**Issue by andreytaboola** [man-group/notebooker#184]
Is there a way to support some kind of input widgets like ipywidgets or any others especially drop downs and sliders
Thank you

**Comment by jonbannister** [comment]
This would be great, and we've looked into it, but ipywidgets requires a running kernel in the backend. Notebooker generates and stores static HTML/Javascript outputs from nbconvert so this isn't possible. Interactive tables are possible with `itables` but we haven't found a good story for dropdowns etc. yet.
