### ISSUE TITLE
Improve Windows Installation Instructions

### ISSUE THREAD

**Issue by rbonallo** [man-group/notebooker#21]
Installation instructions don't run successfully/consecutively on a clean Windows machine.
https://notebooker.readthedocs.io/en/latest/setup.html
E.g "pushd ./notebooker/web/static/" fails, dir does not exist in cwd.

**Comment by jonbannister** [comment]
Hi @rbonallo - please have a look at the updated instructions. Let me know if you have any more issues!

**Comment by rbonallo** [comment]
still some issues, "MONGO_HOST=localhost:27017 MONGO_USER= etc" is not a native shell cmd, I guess should be "mongo MONGO_HOST..."?

**Comment by rbonallo** [comment]
I'd love to get to work but still cant get to run unfort.

**Comment by jonbannister** [comment]
Those commands are adding environment variables. I think the equivalent in Windows would be `set MONGO_HOST localhost:27017`. This could definitely be added to the docs

**Comment by jonbannister** [comment]
Environment variables are no longer used by Notebooker - do let us know if you have any more issues.
